### ISSUE TITLE
travis.yml

### ISSUE THREAD

**Issue by gloriaJun** [gloriaJun/til#35]
```yaml
language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
        - npm build
    - stage: publish
      before_script:
        - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      script:
        - npm publish

notifications:
  email: false
  slack:
    rooms:
      - glriaroom:$SLACK_TOKEN#devops
    on_success: change # default : always
    on_failure: always # default : always
```
